server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Manoj@1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8085


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerbufferSize: 10
        failureRateThreshold: 50
        minimumNumberoOfCalls: 5
        automaticTransititonFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelBreaker:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-periods: 4s
        limit-for-period: 2
        timeout-duration: 2s