server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Manoj@1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#    appname: ${spring.application.name}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
